import { MigrationInterface, QueryRunner } from 'typeorm';

/**
 * 변경 이력(감사 로그) 테이블. 마스터 데이터 쓰기 경로의 누가/언제/무엇을 기록.
 * (AuditLogEntity 와 1:1)
 */
export class CreateAuditLogTable1781914000000 implements MigrationInterface {
  name = 'CreateAuditLogTable1781914000000';

  public async up(q: QueryRunner): Promise<void> {
    if (
      !(await this.exists(q, 'USER_TABLES', 'TABLE_NAME', 'TMDM_AUDIT_LOG'))
    ) {
      await q.query(`CREATE TABLE TMDM_AUDIT_LOG (
        AUDIT_ID    NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL ENABLE,
        ENTITY_TYPE VARCHAR2(40)   NOT NULL ENABLE,
        ENTITY_ID   VARCHAR2(100),
        ACTION      VARCHAR2(10)   NOT NULL ENABLE,
        ACTOR_ID    VARCHAR2(50)   NOT NULL ENABLE,
        SOURCE      VARCHAR2(20)   NOT NULL ENABLE,
        CHANGES     CLOB,
        SUMMARY     VARCHAR2(1000),
        CREATED_AT  TIMESTAMP(6)   DEFAULT SYSTIMESTAMP NOT NULL ENABLE,
        CONSTRAINT PK_TMDM_AUDIT_LOG PRIMARY KEY (AUDIT_ID)
      )`);
    }
    if (
      !(await this.exists(
        q,
        'USER_INDEXES',
        'INDEX_NAME',
        'IX_TMDM_AUDIT_ENTITY',
      ))
    ) {
      await q.query(
        `CREATE INDEX IX_TMDM_AUDIT_ENTITY ON TMDM_AUDIT_LOG (ENTITY_TYPE, ENTITY_ID, CREATED_AT)`,
      );
    }
    if (
      !(await this.exists(
        q,
        'USER_INDEXES',
        'INDEX_NAME',
        'IX_TMDM_AUDIT_ACTOR',
      ))
    ) {
      await q.query(
        `CREATE INDEX IX_TMDM_AUDIT_ACTOR ON TMDM_AUDIT_LOG (ACTOR_ID, CREATED_AT)`,
      );
    }
  }

  public async down(q: QueryRunner): Promise<void> {
    if (await this.exists(q, 'USER_TABLES', 'TABLE_NAME', 'TMDM_AUDIT_LOG')) {
      await q.query(`DROP TABLE TMDM_AUDIT_LOG CASCADE CONSTRAINTS PURGE`);
    }
  }

  private async exists(
    q: QueryRunner,
    view: string,
    column: string,
    name: string,
  ): Promise<boolean> {
    const rows = (await q.query(
      `SELECT COUNT(*) AS CNT FROM ${view} WHERE ${column} = :1`,
      [name],
    )) as Array<{ CNT: number }>;
    const cnt = rows?.[0]?.CNT ?? (rows?.[0] as unknown as number[])?.[0] ?? 0;
    return Number(cnt) > 0;
  }
}
