import { MigrationInterface, QueryRunner } from 'typeorm';

/**
 * 앱 소유 스키마 베이스라인.
 *
 * 개발 DB의 실제 DDL(DBMS_METADATA)에서 추출한 현재 상태 스냅샷이다.
 * 외부에서 이미 관리되는 8개 테이블(DRW_PARAM_INFO, DW_HNT_CLASSIFICATION,
 * DW_SPEC_PLM_TIRE, PTBSPEC, PTBSPECITEM, T_IF_GC_MAND_TEST_INFO_4_IPLM,
 * V_MCODE_INFO_4_HINT, V_PIC_MATTR_MDPT_INFO_4_HINT)은 포함하지 않는다.
 *
 * 멱등: 객체가 이미 있으면 생성하지 않는다. 따라서 기존 개발 DB에서는
 * 아무것도 만들지 않고(no-op) 적용 기록만 남으며, 빈 운영 DB에서는 전체를
 * 신규 생성한다. (시드 데이터는 scripts/seed-auth.cjs 가 담당)
 *
 * ⚠️ down()은 앱 테이블과 그 데이터를 전부 삭제한다. 공용 DB에서 revert 금지.
 */
export class BaselineAppSchema1781913600000 implements MigrationInterface {
  name = 'BaselineAppSchema1781913600000';

  // 생성 순서(드롭은 역순). 테이블 간 FK 는 없으므로 순서는 가독성용이다.
  private readonly tables: { name: string; ddl: string }[] = [
    {
      name: 'TMDM_ROLE',
      ddl: `CREATE TABLE TMDM_ROLE (
        ROLE_ID       VARCHAR2(50)  NOT NULL ENABLE,
        ROLE_NM       VARCHAR2(100) NOT NULL ENABLE,
        IS_SYSTEM_YN  VARCHAR2(1)   DEFAULT 'N',
        SORT_ORDER    NUMBER,
        USE_YN        VARCHAR2(1)   DEFAULT 'Y',
        CONSTRAINT PK_TMDM_ROLE PRIMARY KEY (ROLE_ID)
      )`,
    },
    {
      name: 'TMDM_USER',
      ddl: `CREATE TABLE TMDM_USER (
        USER_ID        VARCHAR2(50)  NOT NULL ENABLE,
        USER_NM        VARCHAR2(100),
        USER_NM_ENG    VARCHAR2(100),
        TEAM_NM        VARCHAR2(100),
        TEAM_NM_ENG    VARCHAR2(100),
        PASSWORD_HASH  VARCHAR2(200),
        AUTH_SOURCE    VARCHAR2(10)  DEFAULT 'LOCAL',
        ROLE_ID        VARCHAR2(50),
        USE_YN         VARCHAR2(1)   DEFAULT 'Y',
        CREATED_AT     TIMESTAMP(6)  DEFAULT SYSTIMESTAMP,
        UPDATED_AT     TIMESTAMP(6)  DEFAULT SYSTIMESTAMP,
        PREFERENCES    VARCHAR2(2000),
        CONSTRAINT PK_TMDM_USER PRIMARY KEY (USER_ID)
      )`,
    },
    {
      name: 'TMDM_MENU',
      ddl: `CREATE TABLE TMDM_MENU (
        MENU_ID     VARCHAR2(100) NOT NULL ENABLE,
        PARENT_ID   VARCHAR2(100),
        MENU_TYPE   VARCHAR2(10)  NOT NULL ENABLE,
        MENU_NM     VARCHAR2(100),
        I18N_KEY    VARCHAR2(100),
        SORT_ORDER  NUMBER,
        USE_YN      VARCHAR2(1)   DEFAULT 'Y',
        CONSTRAINT PK_TMDM_MENU PRIMARY KEY (MENU_ID)
      )`,
    },
    {
      name: 'TMDM_ROLE_MENU_PERM',
      ddl: `CREATE TABLE TMDM_ROLE_MENU_PERM (
        ROLE_ID        VARCHAR2(50)  NOT NULL ENABLE,
        MENU_ID        VARCHAR2(100) NOT NULL ENABLE,
        CAN_VIEW_YN    VARCHAR2(1)   DEFAULT 'N',
        CAN_CREATE_YN  VARCHAR2(1)   DEFAULT 'N',
        CAN_UPDATE_YN  VARCHAR2(1)   DEFAULT 'N',
        CAN_DELETE_YN  VARCHAR2(1)   DEFAULT 'N',
        CAN_APPROVE_YN VARCHAR2(1)   DEFAULT 'N' NOT NULL ENABLE,
        CONSTRAINT PK_TMDM_ROLE_MENU_PERM PRIMARY KEY (ROLE_ID, MENU_ID)
      )`,
    },
    {
      name: 'TMDM_NOTIFICATION',
      ddl: `CREATE TABLE TMDM_NOTIFICATION (
        NOTI_ID       NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL ENABLE,
        RECIPIENT_ID  VARCHAR2(50)  NOT NULL ENABLE,
        NOTI_TYPE     VARCHAR2(40)  NOT NULL ENABLE,
        MESSAGE       VARCHAR2(500) NOT NULL ENABLE,
        LINK          VARCHAR2(200),
        IS_READ_YN    VARCHAR2(1)   DEFAULT 'N' NOT NULL ENABLE,
        CREATED_AT    TIMESTAMP(6)  DEFAULT SYSTIMESTAMP NOT NULL ENABLE,
        CONSTRAINT PK_TMDM_NOTIFICATION PRIMARY KEY (NOTI_ID)
      )`,
    },
    {
      name: 'TMDM_CHANGE_REQUEST',
      ddl: `CREATE TABLE TMDM_CHANGE_REQUEST (
        CR_ID          NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL ENABLE,
        TARGET_TYPE    VARCHAR2(40)  NOT NULL ENABLE,
        OPERATION      VARCHAR2(10)  NOT NULL ENABLE,
        TARGET_ID      NUMBER,
        PAYLOAD        VARCHAR2(4000),
        SUMMARY        VARCHAR2(500),
        REQUESTER_ID   VARCHAR2(50)  NOT NULL ENABLE,
        STATUS         VARCHAR2(10)  DEFAULT 'PENDING' NOT NULL ENABLE,
        REVIEWER_ID    VARCHAR2(50),
        REVIEW_COMMENT VARCHAR2(500),
        CREATED_AT     TIMESTAMP(6)  DEFAULT SYSTIMESTAMP NOT NULL ENABLE,
        REVIEWED_AT    TIMESTAMP(6),
        CONSTRAINT PK_TMDM_CHANGE_REQUEST PRIMARY KEY (CR_ID)
      )`,
    },
    {
      name: 'DW_STD_CODE',
      ddl: `CREATE TABLE DW_STD_CODE (
        CODE_GRP_ID  VARCHAR2(100)  NOT NULL ENABLE,
        CODE_GRP_NM  VARCHAR2(200),
        CODE_LVL     NUMBER(10,0)   NOT NULL ENABLE,
        PARENT_CD    VARCHAR2(100),
        CODE_CD      VARCHAR2(100)  NOT NULL ENABLE,
        CODE_NM      VARCHAR2(200),
        CODE_DESC    VARCHAR2(1000),
        ATTR1_VAL    VARCHAR2(500),
        ATTR1_NM     VARCHAR2(200),
        ATTR1_DESC   VARCHAR2(1000),
        ATTR2_VAL    VARCHAR2(500),
        ATTR2_NM     VARCHAR2(200),
        ATTR2_DESC   VARCHAR2(1000),
        ATTR3_VAL    VARCHAR2(500),
        ATTR3_NM     VARCHAR2(200),
        ATTR3_DESC   VARCHAR2(1000),
        USE_YN       VARCHAR2(1),
        SORT_ORDER   NUMBER(10,0),
        REG_DTM      TIMESTAMP(6),
        UPD_DTM      TIMESTAMP(6),
        CONSTRAINT PK_DW_STD_CODE PRIMARY KEY (CODE_GRP_ID, CODE_LVL, CODE_CD)
      )`,
    },
    {
      name: 'TEMPLATE_STD_TEST_ITEM',
      ddl: `CREATE TABLE TEMPLATE_STD_TEST_ITEM (
        TMPLT_ID                 NUMBER(10,0)  NOT NULL ENABLE,
        PRODUCT_LINE             VARCHAR2(10)  NOT NULL ENABLE,
        TEST_ITEM_NAME           VARCHAR2(100) NOT NULL ENABLE,
        TEST_MTH_NAME            VARCHAR2(100),
        TEST_CDN_NAME            VARCHAR2(100),
        ENDUR_SVRTY              NUMBER(5,0),
        CERTI_TEST_YN            VARCHAR2(10),
        CERTI_TYPE               VARCHAR2(50),
        TEMP_TIRE                VARCHAR2(10),
        SNOW_MARK                VARCHAR2(10),
        FRT                      VARCHAR2(10),
        UTQG                     VARCHAR2(10),
        POR                      VARCHAR2(10),
        RADIAL_BIAS              VARCHAR2(10),
        RIM_INCH                 VARCHAR2(50),
        GRV_DEPTH                VARCHAR2(50),
        SS                       VARCHAR2(200),
        LI                       VARCHAR2(50),
        PLY_RATING               VARCHAR2(50),
        TL_INDICATOR             VARCHAR2(10),
        TBR_POSITION             VARCHAR2(10),
        TBR_GRV_3                VARCHAR2(50),
        TBR_SEGMENT              VARCHAR2(50),
        TBR_ITEM_CNT_PER_BARCODE VARCHAR2(50),
        NEW_SIZE_YN              VARCHAR2(10),
        SIZE_SMPL                VARCHAR2(200),
        F1 NUMBER(1,0), F2 NUMBER(1,0), F3 NUMBER(1,0),
        A0 NUMBER(1,0), A1 NUMBER(1,0), A2 NUMBER(1,0), A3 NUMBER(1,0),
        A4 NUMBER(1,0), A5 NUMBER(1,0), A6 NUMBER(1,0), A7 NUMBER(1,0),
        A8 NUMBER(1,0), A9 NUMBER(1,0),
        N1 NUMBER(1,0), N2 NUMBER(1,0), N3 NUMBER(1,0),
        E1 NUMBER(1,0), E2 NUMBER(1,0), E3 NUMBER(1,0),
        E4 NUMBER(1,0), E5 NUMBER(1,0), E6 NUMBER(1,0),
        K1 NUMBER(1,0),
        M1 NUMBER(1,0), M2 NUMBER(1,0), M3 NUMBER(1,0),
        M4 NUMBER(1,0), M5 NUMBER(1,0), M6 NUMBER(1,0),
        NA NUMBER(1,0),
        L1 NUMBER(1,0), L2 NUMBER(1,0), L3 NUMBER(1,0), L4 NUMBER(1,0),
        L5 NUMBER(1,0), L6 NUMBER(1,0), L7 NUMBER(1,0), L8 NUMBER(1,0),
        CREATED_AT  VARCHAR2(8)  NOT NULL ENABLE,
        CREATED_BY  VARCHAR2(20) NOT NULL ENABLE,
        CDN_PATTERN VARCHAR2(60),
        CONSTRAINT CK_TEMPLATE_STD_TEST_ITEM_PL CHECK (PRODUCT_LINE IN ('PCR', 'LTR', 'TBR')) ENABLE,
        CONSTRAINT PK_TEMPLATE_STD_TEST_ITEM PRIMARY KEY (TMPLT_ID)
      )`,
    },
  ];

  private readonly indexes: { name: string; ddl: string }[] = [
    {
      name: 'IX_TMDM_NOTI_RECIPIENT',
      ddl: `CREATE INDEX IX_TMDM_NOTI_RECIPIENT ON TMDM_NOTIFICATION (RECIPIENT_ID, IS_READ_YN)`,
    },
    {
      name: 'IX_TMDM_CR_STATUS',
      ddl: `CREATE INDEX IX_TMDM_CR_STATUS ON TMDM_CHANGE_REQUEST (STATUS, CREATED_AT)`,
    },
  ];

  // 신규 PK 발번용. 빈 운영 DB 가정으로 START WITH 1.
  // (운영을 데이터와 함께 적재한다면 MAX(TMPLT_ID) 초과로 별도 조정 필요)
  private readonly sequence = {
    name: 'SEQ_TEMPLATE_STD_TEST_ITEM',
    ddl: `CREATE SEQUENCE SEQ_TEMPLATE_STD_TEST_ITEM MINVALUE 1 INCREMENT BY 1 START WITH 1 NOCACHE NOORDER NOCYCLE`,
  };

  public async up(q: QueryRunner): Promise<void> {
    for (const t of this.tables) {
      if (!(await this.exists(q, 'USER_TABLES', 'TABLE_NAME', t.name))) {
        await q.query(t.ddl);
      }
    }
    for (const ix of this.indexes) {
      if (!(await this.exists(q, 'USER_INDEXES', 'INDEX_NAME', ix.name))) {
        await q.query(ix.ddl);
      }
    }
    if (
      !(await this.exists(
        q,
        'USER_SEQUENCES',
        'SEQUENCE_NAME',
        this.sequence.name,
      ))
    ) {
      await q.query(this.sequence.ddl);
    }
  }

  public async down(q: QueryRunner): Promise<void> {
    // ⚠️ 앱 스키마와 데이터를 전부 제거한다. 신규 DB 롤백 용도로만 사용할 것.
    if (
      await this.exists(
        q,
        'USER_SEQUENCES',
        'SEQUENCE_NAME',
        this.sequence.name,
      )
    ) {
      await q.query(`DROP SEQUENCE ${this.sequence.name}`);
    }
    for (const t of [...this.tables].reverse()) {
      if (await this.exists(q, 'USER_TABLES', 'TABLE_NAME', t.name)) {
        // 인덱스는 테이블과 함께 제거된다.
        await q.query(`DROP TABLE ${t.name} CASCADE CONSTRAINTS PURGE`);
      }
    }
  }

  /** Oracle 데이터 딕셔너리에 객체가 존재하는지 확인. */
  private async exists(
    q: QueryRunner,
    view: string,
    column: string,
    name: string,
  ): Promise<boolean> {
    const rows = (await q.query(
      `SELECT COUNT(*) AS CNT FROM ${view} WHERE ${column} = :1`,
      [name],
    )) as Array<{ CNT: number }>;
    const cnt = rows?.[0]?.CNT ?? (rows?.[0] as unknown as number[])?.[0] ?? 0;
    return Number(cnt) > 0;
  }
}
